package entities;

public enum actionType {

    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,

    GET_ALL_CITIES_REQUEST,
    GET_ALL_CITIES_RESPONSE,

    UPDATE_PRICE_REQUEST,
    UPDATE_PRICE_SUCCESS,
    GET_PRICE_REQUEST,
    APPROVE_PRICE_REQUEST,
    APPROVE_PRICE_SUCCESS,

    ERROR
}
