package main.java.common;

public enum actionType {

    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,

    GET_ALL_CITIES_REQUEST,
    GET_ALL_CITIES_RESPONSE,

    UPDATE_PRICE_REQUEST,
    UPDATE_PRICE_SUCCESS,
    GET_PRICE_REQUEST,
    APPROVE_PRICE_REQUEST,
    APPROVE_PRICE_SUCCESS,

    ERROR,
    GET_CITY_NAMES_REQUEST,
    GET_CITY_NAMES_RESPONSE,

    GET_MAPS_REQUEST,
    GET_MAPS_RESPONSE,

    GET_VERSIONS_REQUEST,
    GET_VERSIONS_RESPONSE,

    GET_CATALOG_REQUEST,
    GET_CATALOG_RESPONSE
}